# Generated by Django 4.0.3 on 2022-03-05 06:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maintainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('mobile_number', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator('^(\\+\\d{1,2}\\s?)?1?\\-?\\.?\\s?\\(?\\d{3}\\)?[\\s.-]?\\d{3}[\\s.-]?\\d{4}$', 'Allows all possible mobile numbers')])),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email_address')),
                ('is_verified', models.BooleanField(default=False)),
                ('exipiration_time', models.DateTimeField()),
                ('otp_hex', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
