# Generated by Django 4.0.3 on 2022-03-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_maintainer_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintainer',
            name='expiration_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
