# Generated by Django 4.0.3 on 2022-03-06 11:11

import apps.sensors.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph', models.DecimalField(decimal_places=2, max_digits=4)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tds', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data_datetime', models.DateTimeField(default=apps.sensors.models.get_ist_time)),
            ],
        ),
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('sensorID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('location', models.TextField()),
                ('city', models.TextField()),
            ],
        ),
    ]
