# Generated by Django 4.0.3 on 2022-03-06 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='data_datetime',
        ),
    ]
