# Generated by Django 4.0.3 on 2022-03-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_remove_sensors_latitude_remove_sensors_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensors',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=12, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensors',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=34, max_digits=9),
            preserve_default=False,
        ),
    ]
