# Generated by Django 4.0.3 on 2022-03-06 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_sensors_latitude_sensors_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensors',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='sensors',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
